import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MathJaxContext } from "better-react-mathjax";
import "app/styles/mathlive-font.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const config = {
  loader: { load: ["[tex]/ams"] },
  tex: {
    inlineMath: [
      ["$", "$"],
      ["\\(", "\\)"],
    ],
    displayMath: [
      ["$$", "$$"],
      ["\\[", "\\]"],
    ],
    packages: { "[+]": ["ams"] },
  },
  chtml: {
    fontURL: "/fonts/mathlive", // public/fonts/mathlive 폴더에 위치
  },
};

export const metadata: Metadata = {
  title: "Leave A Trace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <MathJaxContext config={config} version={3}>
          <main className="flex items-center justify-center w-full h-screen">
            <div className="flex flex-col items-center w-full h-full bg-white rounded-lg shadow-lg">
              {children}
            </div>
          </main>
        </MathJaxContext>
      </body>
    </html>
  );
}
