import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MathJaxContext } from "better-react-mathjax";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MathJaxContext>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-300`}
        >
          <main className="flex items-center justify-center w-full h-screen">
            <div className="flex flex-col items-center w-4/5 h-[80%] bg-white rounded-lg shadow-lg p-6">
              {children}
            </div>
          </main>
        </body>
      </html>
    </MathJaxContext>
  );
}
